### ISSUE TITLE
Introduce a secondaryIDs

### ISSUE THREAD

**Issue by lightsprint09** [derhuerst/db-stations#11]
If a station would contain a property like `secondaryIDs ` which contains all evaIds that are not `isMain`. This could help us to build a better mapping

**Comment by derhuerst** [comment]
This would be a good fit for `full.ndjson`. Will implement it.

**Comment by derhuerst** [comment]
Addressed this in 8438ca23051565f60b723281f4fa49b717ec820b. The new data will be published to npm once the build has succeeded.

**Comment by lightsprint09** [comment]
You are so fast! Thanks again 💯
