### ISSUE TITLE
Wrong main EVAId

### ISSUE THREAD

**Issue by lightsprint09** [derhuerst/db-stations#5]
Hey.

Are you sure you could always use the first element here.

https://github.com/derhuerst/db-stations/blob/28f80dd5b4bfbd01d5e2c3cb7c50794506f8d064/build/parse-full.js#L14

https://github.com/derhuerst/db-stations/blob/28f80dd5b4bfbd01d5e2c3cb7c50794506f8d064/build/parse-simplified.js#L11

**Comment by derhuerst** [comment]
> Are you sure you could always use the first element here.

No, not at all. Tell me how to pick the right one!

**Comment by derhuerst** [comment]
Fixed as of a153c9efe74e5dcd8a371f1982f53820d4ab8765, will publish to npm now.

**Comment by lightsprint09** [comment]
Is it already published? Version is still 1.0.0

**Comment by derhuerst** [comment]
@lightsprint09 Finally published `db-stations@1.0.1`.
