### ISSUE TITLE
Release on GitHub & npm are out of sync

### ISSUE THREAD

**Issue by lightsprint09** [derhuerst/db-stations#9]
It is kind of confusion to have a different release history at GitHub and npm

**Comment by derhuerst** [comment]
The GitHub releases are outdated. I don't intend to keep them up to date for now, except if you point to a simple tool to deploy to GitHub releases.

[npm releases get published by Travis CI regularly](https://travis-ci.org/derhuerst/db-stations), so that the module contains up-to-date data.
